<a href="https://colab.research.google.com/github/PacktPublishing/Modern-Computer-Vision-with-PyTorch-2E/blob/main/Chapter02/Auto_gradient_of_tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import torch
x = torch.tensor([[2., -1.], [1., 1.]], requires_grad=True)
print(x)

tensor([[ 2., -1.],
        [ 1.,  1.]], requires_grad=True)


In [2]:
out = x.pow(2).sum()

In [3]:
out.backward()

In [4]:
x.grad

tensor([[ 4., -2.],
        [ 2.,  2.]])

In [17]:
W[0].shape

torch.Size([3, 2])

In [15]:
x.view(2, 1).shape

torch.Size([2, 1])

In [40]:
x = torch.tensor([1.,1.], requires_grad=True)
y = torch.tensor([0.], requires_grad=True)

W = [
    torch.tensor([[-0.0053, 0.3793],
              [-0.5820, -0.5204],
              [-0.2723, 0.1896]], dtype=torch.float32).T, 
    torch.tensor([-0.0140, 0.5607, -0.0628], dtype=torch.float32), 
    torch.tensor([[ 0.1528, -0.1745, -0.1135]], dtype=torch.float32).T, 
    torch.tensor([-0.5516], dtype=torch.float32)
]
W = [i.clone().detach().requires_grad_(True) for i in W]

def forward_pass(x, y, weights):
    pre_hidden = torch.matmul(x, weights[0]) + weights[1]
    hidden = torch.sigmoid(pre_hidden)
    pre_out = torch.matmul(hidden, weights[2]) + weights[3]
    loss = torch.sum(torch.pow((pre_out - y), 2))
    return loss

loss = forward_pass(x, y, weights=W)
loss

tensor(0.3346, grad_fn=<SumBackward0>)

In [41]:
loss.backward()
print([w.grad for w in W])

[tensor([[-0.0428,  0.0469,  0.0327],
        [-0.0428,  0.0469,  0.0327]]), tensor([-0.0428,  0.0469,  0.0327]), tensor([[-0.6814],
        [-0.4255],
        [-0.5364]]), tensor([-1.1568])]


### Computing gradients for the same case that was present in `Chain_rule.ipynb` notebook in previous chapter

In [42]:
x = np.array([[1,1]])
y = np.array([[0]])
x, y = [torch.tensor(i).float() for i in [x,y]]

In [43]:
W = [
    np.array([[-0.0053, 0.3793],
              [-0.5820, -0.5204],
              [-0.2723, 0.1896]], dtype=np.float32).T, 
    np.array([-0.0140, 0.5607, -0.0628], dtype=np.float32), 
    np.array([[ 0.1528, -0.1745, -0.1135]], dtype=np.float32).T, 
    np.array([-0.5516], dtype=np.float32)
]

W = [torch.tensor(i, requires_grad=True) for i in W]

In [44]:
def feed_forward(inputs, outputs, weights):
    pre_hidden = torch.matmul(inputs,weights[0])+ weights[1]
    hidden = 1/(1+torch.exp(-pre_hidden))
    out = torch.matmul(hidden, weights[2]) + weights[3]
    mean_squared_error = torch.mean(torch.square(out - outputs))
    return mean_squared_error

In [45]:
loss = feed_forward(x, y, W)
loss

tensor(0.3346, grad_fn=<MeanBackward0>)

In [46]:
loss.backward()

In [47]:
print([w.grad for w in W])

[tensor([[-0.0428,  0.0469,  0.0327],
        [-0.0428,  0.0469,  0.0327]]), tensor([-0.0428,  0.0469,  0.0327]), tensor([[-0.6814],
        [-0.4255],
        [-0.5364]]), tensor([-1.1568])]


In [48]:
updated_W = [w-w.grad for w in W]
updated_W

[tensor([[ 0.0375, -0.6289, -0.3050],
         [ 0.4221, -0.5673,  0.1569]], grad_fn=<SubBackward0>),
 tensor([ 0.0288,  0.5138, -0.0955], grad_fn=<SubBackward0>),
 tensor([[0.8342],
         [0.2510],
         [0.4229]], grad_fn=<SubBackward0>),
 tensor([0.6052], grad_fn=<SubBackward0>)]