<a href="https://colab.research.google.com/github/PacktPublishing/Modern-Computer-Vision-with-PyTorch-2E/blob/main/Chapter02/Initializing_a_tensor.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
x = torch.tensor([[1,2]])
y = torch.tensor([[1],
                  [2]])

In [2]:
print(x.shape)
# torch.Size([1,2]) # one entity of two items
print(y.shape)
# torch.Size([2,1]) # two entities of one item each
print(x.dtype)
# torch.int64

torch.Size([1, 2])
torch.Size([2, 1])
torch.int64


In [4]:
x = torch.tensor([False, 1, True])
print(x)
# tensor([0., 1., 2.])

tensor([0, 1, 1])


In [5]:
torch.zeros((3, 4))

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [6]:
torch.ones((3, 4))

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [8]:
torch.randint(low=0, high=11, size=(3,4))

tensor([[ 3,  5,  5,  3],
        [ 3,  2, 10,  0],
        [ 0,  6,  1,  0]])

In [9]:
torch.rand(3, 4)

tensor([[0.2946, 0.2610, 0.0958, 0.2530],
        [0.6717, 0.5887, 0.1738, 0.4240],
        [0.2593, 0.7267, 0.4082, 0.2542]])

In [10]:
torch.randn((3,4))

tensor([[-1.1028, -0.4659, -0.1631, -0.1053],
        [ 0.7659,  0.9260, -1.5299, -1.8141],
        [ 0.5430, -0.6561, -0.1048,  0.0427]])

In [11]:
import numpy as np
x = np.array([[10,20,30],[2,3,4]])
y = torch.tensor(x)
print(type(x), type(y))

<class 'numpy.ndarray'> <class 'torch.Tensor'>
