<a href="https://colab.research.google.com/github/PacktPublishing/Modern-Computer-Vision-with-PyTorch-2E/blob/main/Chapter01/Feed_forward_propagation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Forward Propagation

In [13]:
import numpy as np

def feed_forward(inputs, outputs, weights):       
    pre_hidden = np.dot(inputs, weights[0])+ weights[1]
    print(pre_hidden)
    hidden = 1 / (1+np.exp(-pre_hidden))
    print(hidden)
    
    pred_out = np.dot(hidden, weights[2]) + weights[3]
    print(pred_out)
    mean_squared_error = np.mean(np.square(pred_out - outputs))
    return mean_squared_error

In [14]:
inputs = np.array([1, 1])
outputs = np.array([0])
weights = [[[0.1, 0.2, 0.3], [0.4, 0.5, 0.6]], np.array([0.7, 0.8, 0.9]), np.array([0.7, 0.8, 0.9]), np.array([0.7])]
weights

[[[0.1, 0.2, 0.3], [0.4, 0.5, 0.6]],
 array([0.7, 0.8, 0.9]),
 array([0.7, 0.8, 0.9]),
 array([0.7])]

In [15]:
mean_squared_error = feed_forward(inputs, outputs, weights)
mean_squared_error

[1.2 1.5 1.8]
[0.76852478 0.81757448 0.85814894]
[2.66436097]


np.float64(7.09881938375496)